name: cleancodearchitecture
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.7.3'

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.17
  english_words: ^4.0.0
  provider: ^6.0.0
  pdf: ^3.9.0
  path_provider: ^2.0.13

#  syncfusion_flutter_pdfviewer: ^20.4.51
#  flutter_pdfview: ^1.2.5
  printing: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/sonali-bank-logo.png